using System;
using System.Runtime.InteropServices;
using System.Security;

namespace Arisen.Native.RHI
{
    /// <summary>
    /// Manually-maintained P/Invoke sidecar for RHICommandBufferAPI entry points that are not
    /// surfaced by the autogenerated bindings. Keep this file in sync with
    /// Arisen/Development/PackageGame/Local/com.arisen.core.native/Source/Core.RHI/Bridges/RHICommandBufferBridge.cpp.
    /// </summary>
    public static class RHICommandBufferExtAPI
    {
        private const string DllName = "Core.RHI.dll";

        [SuppressUnmanagedCodeSecurity, DllImport(DllName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void RHICommandBuffer_TransitionImageLayoutWithQueueFamily(
            IntPtr cb, RHIImageHandle image, int oldLayout, int targetLayout,
            uint srcQueueFamilyIndex, uint dstQueueFamilyIndex);
    }
}

namespace ArisenEngine.Core.RHI
{
    /// <summary>
    /// Queue-family sentinel values used with
    /// <see cref="RHICommandBuffer.TransitionImageLayout(RHIImageHandle, EImageLayout, EImageLayout, uint, uint)"/>
    /// for cross-API ownership transfers on shared images.
    /// </summary>
    public static class RHIQueueFamily
    {
        /// <summary>In-family transition; no ownership transfer. Mirrors VK_QUEUE_FAMILY_IGNORED.</summary>
        public const uint Ignored = 0xFFFFFFFFu;

        /// <summary>
        /// External API ownership (e.g. D3D11 accessing a shared Win32 NT handle).
        /// Mirrors VK_QUEUE_FAMILY_EXTERNAL_KHR.
        /// </summary>
        public const uint External = 0xFFFFFFFDu;
    }
}
